### ISSUE TITLE
Change platform from Eagle to Kicad

### ISSUE THREAD

**Issue by microwiz** [brainsmoke/baduino#1]
Change platform from Eagle to Kicad. The project lists Eagle as development platform while the brd files are designed in KiCAD.

**Comment by brainsmoke** [comment]
That's an automatic thing by github, I dont think I can change that.

**Comment by microwiz** [comment]
In that case you should leave a feedback or contact github. I have seen several projects using Kicad as the platform. Anyways I'm not bothered but just wanted to improve.
